package com.koval.jresolver.rules

import com.koval.jresolver.common.api.bean.issue.Issue;

global java.util.List results

rule "Description size should be more than 100 characters"
	when
		$issue : Issue( description.length < 100 )
	then
		results.add("Description size should be more than 100 characters");
end


rule "Description contains word 'file'"
	when
		$issue : Issue( description contains "file" )
	then
		results.add("Description contains word 'file', hence the issue should contain attachments");
end