package com.koval.jresolver.rules

import com.koval.jresolver.common.api.bean.issue.Issue;

global java.util.List results

rule "Comments size should contain at least one comment"
	when
		$issue : Issue( comments.isEmpty() )
	then
		results.add("Comments size should contain at least one comment");
end


rule "Comments less than 5"
	when
		$issue : Issue( comments.size() < 5 )
	then
		results.add("Comments less than 5");
end