package com.koval.jresolver.rules

import com.atlassian.jira.rest.client.api.domain.Issue;

global com.koval.jresolver.rules.results.RulesResult results

rule "Comments size should contain at least one comment"
	when
		$issue : Issue( comments.isEmpty() )
	then
		results.putAdvice("Comments size should contain at least one comment");
end


rule "Comments less than 5"
	when
		$issue : Issue( comments.size() < 5 )
	then
		results.putAdvice("Comments less than 5");
end