package com.koval.jresolver.rules

import com.koval.jresolver.connector.bean.JiraIssue;
import com.koval.jresolver.connector.bean.JiraStatus;

global com.koval.jresolver.rules.results.RulesResult results

rule "Comments size should contain at least one comment"
    when
        $issue : JiraIssue( comments.isEmpty() )
    then
        results.putAdvice("Comments size should contain at least one comment");
end


rule "Comments less than 5"
    when
        $issue : JiraIssue( comments.size() < 5 )
    then
        results.putAdvice("Comments less than 5");
end