
package com.koval.jresolver.rules

import com.koval.jresolver.connector.bean.JiraIssue;
import com.koval.jresolver.connector.bean.JiraStatus;

global com.koval.jresolver.rules.results.RulesResult results

rule "Claim more information"
    dialect "mvel"
    when
        m : JiraIssue( description.length < 5, comments.size() < 5 )
    then
        System.out.println("Need more details in description");
        results.putAdvice("Need more details in description");
end


rule "Claim more comments"
    dialect "mvel"
    when
        m : JiraIssue( comments.isEmpty() )
    then
        System.out.println("Need more comments");
        results.putAdvice("Need more comments");
end

rule "Check status"
    dialect "mvel"
    when
        m : JiraIssue( status == JiraStatus.CLOSED, comments : comments )
    then
        System.out.println("Need more comments");
        System.out.println(comments);
        results.putAdvice("Need more comments");
end