package com.koval.jresolver.rules

import com.koval.jresolver.connector.jira.bean.JiraIssue;

global RulesResult results

rule "Description size should be more than 100 characters"
	when
		$issue : JiraIssue( description.length < 100 )
	then
		results.putAdvice("Description size should be more than 100 characters");
end


rule "Description contains word 'file'"
	when
		$issue : JiraIssue( description contains "file" )
	then
		results.putAdvice("Description contains word 'file', hence the issue should contain attachments");
end
